version: '3.8'

services:
  backend:
    build:
      context: ./EventWorldApp
      dockerfile: Dockerfile.backend
    container_name: eventworld-backend
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./EventWorldApp:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=eventdb
      - DB_USER=dev2
      - DB_PASSWORD=456123
      - DB_HOST=db
      - DB_PORT=5432

  frontend:
    build:
      context: ./frontend/frontendEventWorld
      dockerfile: Dockerfile.frontend
    container_name: eventworld-frontend
    ports:
      - "5173:5173"
    command: npm run dev
    depends_on:
      - backend

  db:
    image: postgres:13
    container_name: eventworld-db
    environment:
      POSTGRES_DB: eventdb
      POSTGRES_USER: DB_USER
      POSTGRES_PASSWORD: DB_PASSWORD
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
