version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./EventWorldApp/Dockerfile.backend
    container_name: eventworld-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    

  frontend:
    build:
      context: ./frontend/frontendEventWorld
      dockerfile: Dockerfile.frontend
    container_name: eventworld-frontend
    ports:
      - "5173:5173"
    command: npm run dev
    depends_on:
      - backend

  db:
    image: postgres:13
    container_name: eventworld-db
    env_file :
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
