"""
Django settings for eventworld project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/ '"
"""

from pathlib import Path
from datetime import timedelta
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
#BASE_DIR = Path(__file__).resolve().parent.parent
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-gy775*qyy9g-4op4=(u04s16451g1-i-k67=_n4e17jg8%z+)_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# DEBUG = True => css actif http://127.0.0.1:8000/admin/
# DEBUG = False => css non actif http://127.0.0.1:8000/admin/

#ALLOWED_HOSTS = ['127.0.0.1', 'localhost']
ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'EventWorldApp',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',  # Seuls les utilisateurs authentifiés peuvent accéder à l'API
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),  # Le token est valide 1 jour
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),  # Le token de refresh est valide 7 jours
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # AVANT `CommonMiddleware`
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:8000",
]

CORS_ORIGIN_ALLOW_ALL = True
#https://stackoverflow.com/questions/74833288/django-vue3-access-control-allow-origin-is-not-allowed
CORS_ALLOW_METHODS = [
    "GET",
    "POST",
    "PUT",
    "DELETE",
    "OPTIONS"
]

# CORS_ALLOW_HEADERS -> Contrôle les en-têtes que le client (frontend) est autorisé à envoyer à Django
# Lorsqu'on fait une requête Axios vers Django, on peut avoir besoin d’ajouter des en-têtes spécifiques 
# (ex: Content-Type, Authorization, Content-Disposition).
# Sans ça, Django rejetterait les requêtes contenant ces en-têtes.

    # CORS_ALLOW_HEADERS = [
    #     "content-type",
    #     "authorization",
    #     "content-disposition",  # Permet d'envoyer ce header au frontend
    # ]

# CORS_EXPOSE_HEADERS -> Contrôle les en-têtes que Django peut renvoyer et qui seront visibles par le frontend.
# Par défaut, les navigateurs bloquent l’accès aux en-têtes sensibles pour des raisons de sécurité.
# Sans CORS_EXPOSE_HEADERS, le frontend ne verra pas content-disposition dans response.headers.

    # CORS_EXPOSE_HEADERS = [
    #     "content-disposition",  # Permet au frontend d'accéder à cet en-tête
    # ]

ROOT_URLCONF = 'eventworld.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'eventworld.wsgi.application'


# Database '
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'Event_World_db',
        'USER': 'dev2',
        'PASSWORD': '456123',
        'HOST': os.getenv('DB_HOST', 'db'),
        'PORT': '5432',
    }
}
print("🔍 DB_HOST =", os.getenv("DB_HOST"))
# print("🧠 DATABASE CONFIG =", DATABASES['default'])
# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'EventWorldApp.User'


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
