# Utilise l’image officielle Python + Node
FROM mcr.microsoft.com/devcontainers/python:3.11-node

# Installe pip si manquant (précaution)
RUN apt-get update && apt-get install -y python3-pip python3-venv
