# Generated by Django 5.1.7 on 2025-03-07 12:49

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_evenement', models.CharField(help_text='Entrez un code évènement de 13 chiffres.', max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Le code évènement doit contenir exactement 13 chiffres.', regex='^\\d{13}$')])),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price_1', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price_2', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price_3', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price_4', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price_5', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price_6', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('location', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('postal_code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('number_place', models.IntegerField(default=0)),
                ('type_event', models.CharField(choices=[('public', 'Public'), ('private', 'Privé'), ('limited', 'Limité')], default='private', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('current', 'Current'), ('finished', 'Finished'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InvitationNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('accepted', 'Accepted'), ('refused', 'Refused')], default='sent', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='EventWorldApp.evenement')),
            ],
            options={
                'verbose_name': 'Invitation',
                'verbose_name_plural': 'Invitations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100, unique=True)),
                ('company_number', models.CharField(max_length=25, unique=True)),
                ('type_organisator', models.CharField(choices=[('organisateur', 'Organisateur'), ('association', 'Association'), ('etudiant', 'Étudiant'), ('autre', 'Autre')], default='organisateur', max_length=20)),
                ('civility', models.CharField(blank=True, max_length=10, null=True)),
                ('name_contact', models.CharField(max_length=100)),
                ('surname_contact', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=10, null=True)),
                ('landline_phone', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(max_length=200)),
                ('postal_code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profils',
            },
        ),
        migrations.AddField(
            model_name='evenement',
            name='organisator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='EventWorldApp.profil'),
        ),
        migrations.CreateModel(
            name='Ticketing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qr_code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('used', 'Used'), ('invalid', 'Invalid')], default='valid', max_length=20)),
                ('scan_timestamp', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='EventWorldApp.evenement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='EventWorldApp.ticketing')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
