# Generated by Django 5.1.7 on 2025-03-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventWorldApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='price_categories',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
