# Generated by Django 5.1.7 on 2025-03-11 15:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventWorldApp', '0002_evenement_price_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='code_evenement',
            field=models.CharField(blank=True, help_text='Entrez un code évènement de 13 chiffres.', max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Le code évènement doit contenir exactement 13 chiffres.', regex='^\\d{13}$')]),
        ),
    ]
