# Generated by Django 5.1.7 on 2025-03-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventWorldApp', '0003_alter_evenement_code_evenement'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketing',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='ticketing',
            name='firstname',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='ticketing',
            name='lastname',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='ticketing',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='code_evenement',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
