# Generated by Django 5.1.7 on 2025-03-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventWorldApp', '0004_ticketing_email_ticketing_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketing',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
