# Generated by Django 5.1.7 on 2025-03-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventWorldApp', '0005_ticketing_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketing',
            name='type_event',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
