# Generated by Django 5.1.7 on 2025-03-12 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventWorldApp', '0006_ticketing_type_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketing',
            name='type_event',
        ),
    ]
