# Generated by Django 5.1.7 on 2025-03-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventWorldApp', '0007_remove_ticketing_type_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketing',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='ticketing',
            name='firstname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ticketing',
            name='lastname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ticketing',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
