# Generated by Django 5.1.7 on 2025-03-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventWorldApp', '0008_alter_ticketing_email_alter_ticketing_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketing',
            name='ticket_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
