# Generated by Django 5.1.7 on 2025-04-02 07:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventWorldApp', '0009_ticketing_ticket_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryScanner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('can_scan', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_scanners', to='EventWorldApp.evenement')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_scanner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
