# Generated by Django 5.1.7 on 2025-05-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventWorldApp', '0010_temporaryscanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='event_pictures/'),
        ),
    ]
