# Generated by Django 5.1.7 on 2025-05-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventWorldApp', '0011_evenement_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='temp_user_limit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='temporaryscanner',
            name='can_sell',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='temporaryscanner',
            name='tickets_scanned',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='temporaryscanner',
            name='tickets_sold',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
